[package]
name = "p"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "p"
crate-type = ["cdylib"]

[dependencies]
libc = "0.2"
nix = { version = "0.29.0", features = ["signal", "process", "fs"] }
rustler = "0.36.1"
